#!/bin/bash

pdname=HIMinBiasUPC
dataset=/HIMinBiasUPC/davidlw-PR2011_MBPPRereco_TRKANASKIM_v4-2be5f21752c831f670ba8ae18cdae752/USER
njobs=40

### chargedepcorr
tag=pttrg033_ptassallweight_eff1_v8
type=chargedepcorr

### epetadeco
#tag=pttrg033_ptassallweight_etaass4452_eff1_v43
#type=epetadeco

### ebyeflow
#tag=pttrg033_rereco_eff1_v3
#type=ebyeflow

cat > crab_${type}_n100185_pprereco.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_pprereco_n100185_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_n100185_$tag
ui_working_dir =  $pdname/${type}_n100185_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
EOF

cat > crab_${type}_n185260_pprereco.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_pprereco_n185260_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_n185260_$tag
ui_working_dir = $pdname/${type}_n185260_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
EOF

cat > crab_${type}_n260300_pprereco.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_pprereco_n260300_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_n260300_$tag
ui_working_dir = $pdname/${type}_n260300_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
EOF

cat > crab_${type}_n300_pprereco.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_pprereco_n300_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_n300_$tag
ui_working_dir = $pdname/${type}_n300_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
EOF

cat > submit_${type}_pprereco << EOF 
crab -create -cfg crab_${type}_n100185_pprereco.cfg
crab -create -cfg crab_${type}_n185260_pprereco.cfg
crab -create -cfg crab_${type}_n260300_pprereco.cfg
crab -create -cfg crab_${type}_n300_pprereco.cfg
crab -submit 1-400 -c $pdname/${type}_n100185_$tag
crab -submit 401-800 -c $pdname/${type}_n100185_$tag
crab -submit 1-400 -c $pdname/${type}_n185260_$tag
crab -submit 401-800 -c $pdname/${type}_n185260_$tag
crab -submit 1-400 -c $pdname/${type}_n260300_$tag
crab -submit 401-800 -c $pdname/${type}_n260300_$tag
crab -submit 1-400 -c $pdname/${type}_n300_$tag
crab -submit 401-800 -c $pdname/${type}_n300_$tag
EOF

chmod u+x submit_${type}_pprereco

hadoopdir=/mnt/hadoop/cms/store/user/davidlw/$pdname
scratchdir=/export/d00/scratch/davidlw/DiHadronCorrelations/outputs_312/HIData_Minbias_2760GeV/merged
cat > merge_${type}_pprereco << EOF 
nohup hadd -f $scratchdir/${type}_n100185_$tag.root $hadoopdir/${type}_n100185_$tag/*.root > /tmp/nohup.out & 
nohup hadd -f $scratchdir/${type}_n185260_$tag.root $hadoopdir/${type}_n185260_$tag/*.root > /tmp/nohup1.out &
nohup hadd -f $scratchdir/${type}_n260300_$tag.root $hadoopdir/${type}_n260300_$tag/*.root > /tmp/nohup2.out &
nohup hadd -f $scratchdir/${type}_n300_$tag.root $hadoopdir/${type}_n300_$tag/*.root > /tmp/nohup3.out &
EOF

chmod u+x merge_${type}_pprereco
