#!/bin/bash

pdname=MinBias_TuneMonash13_13TeV-pythia8
dataset=/MinBias_TuneMonash13_13TeV-pythia8/davidlw-RecoSkim_batch4_v1-00b3bbd68a41a1bc2b98cf5da8508e09/USER 

nevents=20000

### dihadroncorrelation
tag=monash13_pttrg13_ptass13_eff0_v1
type=dihadroncorrelation

cat > crab_${type}_pp2015_n70.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_pp2015_n70_cfg.py
total_number_of_events   = -1 
events_per_job     = $nevents 
output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_n70_$tag
ui_working_dir = $pdname/${type}_n70_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
EOF

cat > submit_${type}_pp2015 << EOF 
crab -create -submit -cfg crab_${type}_pp2015_n70.cfg
EOF

chmod u+x submit_${type}_pp2015

hadoopdir=/mnt/hadoop/cms/store/user/davidlw/$pdname
scratchdir=/export/d00/scratch/davidlw/DiHadronCorrelations/outputs_312/PythiaReco_Minbias_13TeV/merged
cat > merge_${type}_pp2015 << EOF 
nohup hadd -f $scratchdir/${type}_n70_$tag.root $hadoopdir/${type}_n70_$tag/*.root > /tmp/nohup.out & 
EOF

chmod u+x merge_${type}_pp2015
