#!/bin/bash

dir=`pwd`
ldir=$dir/joblogs
outfile=$1_$2
subfile=$dir/subfiles/subfile_$outfile

cat > $subfile <<EOF

Universe     = vanilla

Notification = Error
Requirements = (Machine != "hibat0009.cmsaf.mit.edu") && (Machine !="t2bat0236.cmsaf.mit.edu") && (Machine !="lnbat0002.cmsaf.mit.edu")
Executable   = $dir/merge_chargedepcorr
Arguments    = $1 $2
Rank         = Mips
GetEnv       = True
priority     = 2000

#initialdir   = $dir
input        = /dev/null
output       = $ldir/$outfile.out
error        = $ldir/$outfile.err
log          = $ldir/$outfile.log

+AccountingGroup = "group_cmshi.$USER"

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

Queue
EOF

condor_submit $subfile
