#!/bin/bash

pdname=Hydjet1p8_TuneDrum_Quenched_MinBias_2760GeV
#dataset=/Hydjet1p8_TuneDrum_Quenched_MinBias_2760GeV/davidlw-RECO_5320_v1-71a485a731d6b2661f997f58ff50f0c0/USER
dataset=/Hydjet1p8_TuneDrum_Quenched_MinBias_2760GeV/davidlw-RECO_pixeltracks_5320_v1-6c39a3733463cd9bceaa11f85fda740d/USER
nevents=10000

### dihadroncorrelation
#tag=pt033_factorization_eff0_v1
#tag=ptall_hf_eff0_v1
#type=dihadroncorrelation

### epptdeco
#tag=pt033_factorization_eff0_v2
#type=epptdeco

### epetadeco
tag=pttrg033_ptassallweight_etaass45_pixel_eff0_v42
type=epetadeco_mc

### ebyeflow
#tag=pttrg13_eff0_v1
#type=ebyeflow

cat > crab_${type}_cent010.cfg << EOF
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent010_cfg.py
total_number_of_events   = -1
events_per_job     = $nevents
output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent010_$tag
ui_working_dir = $pdname/${type}_cent010_$tag
check_user_remote_dir   = 0

[GRID]
max_rss = 3000
se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent1020.cfg << EOF
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent1020_cfg.py
total_number_of_events   = -1
events_per_job     = $nevents
output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent1020_$tag
ui_working_dir = $pdname/${type}_cent1020_$tag
check_user_remote_dir   = 0

[GRID]
max_rss = 3000
se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent2030.cfg << EOF
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent2030_cfg.py
total_number_of_events   = -1
events_per_job     = $nevents
output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent2030_$tag
ui_working_dir = $pdname/${type}_cent2030_$tag
check_user_remote_dir   = 0

[GRID]
max_rss = 3000
se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent3040.cfg << EOF
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent3040_cfg.py
total_number_of_events   = -1
events_per_job     = $nevents
output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent3040_$tag
ui_working_dir = $pdname/${type}_cent3040_$tag
check_user_remote_dir   = 0

[GRID]
max_rss = 3000
se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent4050.cfg << EOF
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent4050_cfg.py
total_number_of_events   = -1
events_per_job     = $nevents
output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent4050_$tag
ui_working_dir = $pdname/${type}_cent4050_$tag
check_user_remote_dir   = 0

[GRID]
max_rss = 3000
se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent5060.cfg << EOF
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent5060_cfg.py
total_number_of_events   = -1
events_per_job     = $nevents
output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent5060_$tag
ui_working_dir = $pdname/${type}_cent5060_$tag
check_user_remote_dir   = 0

[GRID]
max_rss = 3000
se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > submit_${type} << EOF 
crab -create -submit -cfg crab_${type}_cent5060.cfg
crab -create -submit -cfg crab_${type}_cent4050.cfg
crab -create -submit -cfg crab_${type}_cent3040.cfg
crab -create -submit -cfg crab_${type}_cent2030.cfg
crab -create -submit -cfg crab_${type}_cent1020.cfg
crab -create -submit -cfg crab_${type}_cent010.cfg
EOF
chmod u+x submit_${type}

hadoopdir=/mnt/hadoop/cms/store/user/davidlw/$pdname
scratchdir=/export/d00/scratch/davidlw/DiHadronCorrelations/outputs_312/HydjetReco_Minbias_2760GeV/merged
cat > merge_${type}_all << EOF 
nohup hadd -f $scratchdir/${type}_cent5060_$tag.root $hadoopdir/${type}_cent5060_$tag/*.root > /tmp/nohup.out &
nohup hadd -f $scratchdir/${type}_cent4050_$tag.root $hadoopdir/${type}_cent4050_$tag/*.root > /tmp/nohup1.out &
nohup hadd -f $scratchdir/${type}_cent3040_$tag.root $hadoopdir/${type}_cent3040_$tag/*.root > /tmp/nohup2.out &
nohup hadd -f $scratchdir/${type}_cent2030_$tag.root $hadoopdir/${type}_cent2030_$tag/*.root > /tmp/nohup3.out &
nohup hadd -f $scratchdir/${type}_cent1020_$tag.root $hadoopdir/${type}_cent1020_$tag/*.root > /tmp/nohup4.out &
nohup hadd -f $scratchdir/${type}_cent010_$tag.root $hadoopdir/${type}_cent010_$tag/*.root > /tmp/nohup5.out &
EOF
chmod u+x merge_${type}_all
