#!/bin/bash

pdname=HIMinBiasUPC
#datasetucc=/HIMinBiasUPC/davidlw-Skim_rereco_generaltracks_UCC_v1-1407d97c78fb8eac4c87a1e8dfca2bd9/USER
#dataset=/HIMinBiasUPC/davidlw-Skim_rereco_generaltracks_MB_v1-9c1b4b9b6b9ff3e493a474ba7d01bc76/USER
dataset=/HIMinBiasUPC/davidlw-Skim_rereco_MB_pixeltracks_final_v2-9c1b4b9b6b9ff3e493a474ba7d01bc76/USER
datasetucc=/HIMinBiasUPC/davidlw-Skim_rereco_UCC_pixeltracks_final_v2-1407d97c78fb8eac4c87a1e8dfca2bd9/USER
njobs=10

### dihadroncorrelation
#tag=pt033_factorization_eff1_v2
#tag=ptall_hf_eff0_v1
#type=dihadroncorrelation

### epptdeco
#tag=pt033_factorization_eff1_v6
#type=epptdeco

### epetadeco
#tag=pttrg053_ptassallweight_etaass445_eff0_general_v45
#tag=pttrg13_ptassallweight_etaass445_bin08_eff1_v45
#type=epetadeco2

### ebyeflow
#tag=pttrg13_eff0_v1
#type=ebyeflow

### chargedepcorr
tag=pttrg033_ptassallweight_etaass445_eff1_zvtx1_bin01_v45
type=chargedepcorr

cat > crab_${type}_cent002.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $datasetucc
pset                    = ../cfg/${type}_cent002_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
#output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent002_$tag
ui_working_dir = $pdname/${type}_cent002_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent05.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent05_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs
#output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent05_$tag
ui_working_dir = $pdname/${type}_cent05_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent025.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent025_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs
#output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent025_$tag
ui_working_dir = $pdname/${type}_cent025_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent510.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent510_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
#output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent510_$tag
ui_working_dir = $pdname/${type}_cent510_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent1020.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent1020_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
#output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent1020_$tag
ui_working_dir = $pdname/${type}_cent1020_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent2030.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent2030_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
#output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent2030_$tag
ui_working_dir = $pdname/${type}_cent2030_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent3040.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent3040_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
#output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent3040_$tag
ui_working_dir = $pdname/${type}_cent3040_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent4050.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent4050_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
#output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent4050_$tag
ui_working_dir = $pdname/${type}_cent4050_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent5060.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent5060_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
#output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent5060_$tag
ui_working_dir = $pdname/${type}_cent5060_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent6070.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent6070_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
#output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent6070_$tag
ui_working_dir = $pdname/${type}_cent6070_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > crab_${type}_cent7080.cfg << EOF 
[CRAB]
jobtype = cmssw
scheduler = remoteGlidein
use_server   = 0

[CMSSW]
use_dbs3 = 1 
dbs_url                 = phys03
datasetpath             = $dataset
pset                    = ../cfg/${type}_cent7080_cfg.py
total_number_of_lumis   = -1 
lumis_per_job     = $njobs 
#output_file = ${type}.root

[USER]
copy_data               = 1
storage_element         = T2_US_MIT

user_remote_dir = $pdname/${type}_cent7080_$tag
ui_working_dir = $pdname/${type}_cent7080_$tag
check_user_remote_dir   = 0

[GRID]
#max_rss = 3000
#se_white_list = mit.edu
allow_overflow = 0
#max_wall_clock_time=600
EOF

cat > submit_${type} << EOF 
crab -create -cfg crab_${type}_cent7080.cfg
crab -create -cfg crab_${type}_cent6070.cfg
crab -create -cfg crab_${type}_cent5060.cfg
crab -create -cfg crab_${type}_cent4050.cfg
crab -create -cfg crab_${type}_cent3040.cfg
crab -create -cfg crab_${type}_cent2030.cfg
crab -create -cfg crab_${type}_cent1020.cfg
crab -create -cfg crab_${type}_cent510.cfg
crab -create -cfg crab_${type}_cent05.cfg
crab -create -cfg crab_${type}_cent025.cfg
crab -create -cfg crab_${type}_cent002.cfg
crab -submit 1501-2000 -c $pdname/${type}_cent002_$tag
crab -submit 1001-1500 -c $pdname/${type}_cent002_$tag
crab -submit 501-1000 -c $pdname/${type}_cent002_$tag
crab -submit 1-500 -c $pdname/${type}_cent002_$tag
crab -submit 1501-2000 -c $pdname/${type}_cent05_$tag
crab -submit 1001-1500 -c $pdname/${type}_cent05_$tag
crab -submit 501-1000 -c $pdname/${type}_cent05_$tag
crab -submit 1-500 -c $pdname/${type}_cent05_$tag
crab -submit 1501-2000 -c $pdname/${type}_cent025_$tag
crab -submit 1001-1500 -c $pdname/${type}_cent025_$tag
crab -submit 501-1000 -c $pdname/${type}_cent025_$tag
crab -submit 1-500 -c $pdname/${type}_cent025_$tag
crab -submit 1501-2000 -c $pdname/${type}_cent510_$tag
crab -submit 1001-1500 -c $pdname/${type}_cent510_$tag
crab -submit 501-1000 -c $pdname/${type}_cent510_$tag
crab -submit 1-500 -c $pdname/${type}_cent510_$tag
crab -submit 1501-2000 -c $pdname/${type}_cent1020_$tag
crab -submit 1001-1500 -c $pdname/${type}_cent1020_$tag
crab -submit 501-1000 -c $pdname/${type}_cent1020_$tag
crab -submit 1-500 -c $pdname/${type}_cent1020_$tag
crab -submit 1501-2000 -c $pdname/${type}_cent2030_$tag
crab -submit 1001-1500 -c $pdname/${type}_cent2030_$tag
crab -submit 501-1000 -c $pdname/${type}_cent2030_$tag
crab -submit 1-500 -c $pdname/${type}_cent2030_$tag
crab -submit 1501-2000 -c $pdname/${type}_cent3040_$tag
crab -submit 1001-1500 -c $pdname/${type}_cent3040_$tag
crab -submit 501-1000 -c $pdname/${type}_cent3040_$tag
crab -submit 1-500 -c $pdname/${type}_cent3040_$tag
crab -submit 1501-2000 -c $pdname/${type}_cent4050_$tag
crab -submit 1001-1500 -c $pdname/${type}_cent4050_$tag
crab -submit 501-1000 -c $pdname/${type}_cent4050_$tag
crab -submit 1-500 -c $pdname/${type}_cent4050_$tag
crab -submit 1501-2000 -c $pdname/${type}_cent5060_$tag
crab -submit 1001-1500 -c $pdname/${type}_cent5060_$tag
crab -submit 501-1000 -c $pdname/${type}_cent5060_$tag
crab -submit 1-500 -c $pdname/${type}_cent5060_$tag
crab -submit 1501-2000 -c $pdname/${type}_cent6070_$tag
crab -submit 1001-1500 -c $pdname/${type}_cent6070_$tag
crab -submit 501-1000 -c $pdname/${type}_cent6070_$tag
crab -submit 1-500 -c $pdname/${type}_cent6070_$tag
crab -submit 1501-2000 -c $pdname/${type}_cent7080_$tag
crab -submit 1001-1500 -c $pdname/${type}_cent7080_$tag
crab -submit 501-1000 -c $pdname/${type}_cent7080_$tag
crab -submit 1-500 -c $pdname/${type}_cent7080_$tag
EOF

chmod u+x submit_${type}

hadoopdir=/mnt/hadoop/cms/store/user/davidlw/$pdname
scratchdir=/export/d00/scratch/davidlw/DiHadronCorrelations/outputs_312/HIData_Minbias_2760GeV/merged

cat > merge_${type} << EOF 
hadd -f /tmp/${type}_cent\$1_seq\$2_$tag.root $hadoopdir/${type}_cent\$1_$tag/${type}_\$2*.root
scp /tmp/${type}_cent\$1_seq\$2_$tag.root hidsk0001:$scratchdir/
EOF

cat > merge_${type}_all << EOF 
nohup hadd -f $scratchdir/${type}_cent7080_$tag.root $scratchdir/${type}_cent7080_seq*_$tag.root > /tmp/nohup.out &
nohup hadd -f $scratchdir/${type}_cent6070_$tag.root $scratchdir/${type}_cent6070_seq*_$tag.root > /tmp/nohup.out &
nohup hadd -f $scratchdir/${type}_cent5060_$tag.root $scratchdir/${type}_cent5060_seq*_$tag.root > /tmp/nohup.out &
nohup hadd -f $scratchdir/${type}_cent4050_$tag.root $scratchdir/${type}_cent4050_seq*_$tag.root > /tmp/nohup1.out &
nohup hadd -f $scratchdir/${type}_cent3040_$tag.root $scratchdir/${type}_cent3040_seq*_$tag.root > /tmp/nohup2.out &
nohup hadd -f $scratchdir/${type}_cent2030_$tag.root $scratchdir/${type}_cent2030_seq*_$tag.root > /tmp/nohup3.out &
nohup hadd -f $scratchdir/${type}_cent1020_$tag.root $scratchdir/${type}_cent1020_seq*_$tag.root > /tmp/nohup4.out &
nohup hadd -f $scratchdir/${type}_cent510_$tag.root $scratchdir/${type}_cent510_seq*_$tag.root > /tmp/nohup5.out &
nohup hadd -f $scratchdir/${type}_cent05_$tag.root $scratchdir/${type}_cent05_seq*_$tag.root > /tmp/nohup6.out &
nohup hadd -f $scratchdir/${type}_cent025_$tag.root $scratchdir/${type}_cent025_seq*_$tag.root > /tmp/nohup7.out &
nohup hadd -f $scratchdir/${type}_cent002_$tag.root $scratchdir/${type}_cent002_seq*_$tag.root > /tmp/nohup8.out &
EOF

chmod u+x merge_${type}
chmod u+x merge_${type}_all
